services:
  - type: web
    name: marin_ship
    env: python
    plan: free
    pythonVersion: 3.11.8  # نسخه پایدار با imghdr
    buildCommand: pip install -r requirements.txt
    startCommand: python ship_bot.py
